# Generated by Django 5.1 on 2025-01-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100, unique=True)),
                ('unit_amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Destinatarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('numero_casa', models.CharField(max_length=100)),
                ('telefono_fijo', models.CharField(max_length=100)),
                ('telefono_celular', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=100, unique=True)),
                ('municipio', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='nomencladores.municipio')),
                ('provincia', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='nomencladores.provincia')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_session_url', models.URLField(blank=True, max_length=500, null=True)),
                ('checkout_session_success_url', models.URLField(blank=True, max_length=500, null=True)),
                ('checkout_session_cancel_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.destinatarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.precio')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='tienda.DetallePedido', to='tienda.precio'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('default_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_products', to='tienda.precio')),
            ],
        ),
        migrations.AddField(
            model_name='precio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='tienda.producto'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-created_at'], name='tienda_pedi_created_25698d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', '-created_at'], name='tienda_pedi_usuario_5c2b98_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='tienda_pedi_estado_9912bc_idx'),
        ),
    ]
