# Generated by Django 5.1 on 2024-10-27 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-created_at'], name='tienda_pedi_created_25698d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', '-created_at'], name='tienda_pedi_usuario_5c2b98_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='tienda_pedi_estado_9912bc_idx'),
        ),
    ]
