# Generated by Django 5.1 on 2024-09-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
