# Generated by Django 5.1 on 2024-12-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_pedido_tienda_pedi_created_25698d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
    ]
