# Generated by Django 5.1 on 2024-09-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='checkout_session_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
