# Generated by Django 5.1 on 2024-09-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_checkout_session_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='checkout_session_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
