# Generated by Django 5.1 on 2024-09-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_pedido_checkout_session_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='stripe_payment_intent_id',
            new_name='stripe_checkout_session_id',
        ),
    ]
