# Generated by Django 5.1 on 2024-09-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_rename_stripe_payment_intent_id_pedido_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='checkout_session_cancel_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='checkout_session_success_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
