# Generated by Django 5.1 on 2024-09-22 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0001_initial'),
        ('tienda', '0006_pedido_checkout_session_cancel_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_envio',
        ),
        migrations.CreateModel(
            name='Destinatarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('numero_casa', models.CharField(max_length=100)),
                ('telefono_fijo', models.CharField(max_length=100)),
                ('telefono_celular', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=100, unique=True)),
                ('municipio', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='nomencladores.municipio')),
                ('provincia', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='nomencladores.provincia')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='destinatario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.destinatarios'),
            preserve_default=False,
        ),
    ]
