# Generated by Django 5.1 on 2024-09-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_pedido_direccion_envio_destinatarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.destinatarios'),
        ),
    ]
