# Generated by Django 5.1 on 2024-09-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0003_remove_usuario_groups_usuario_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='customer_id',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='customer id'),
        ),
    ]
